---
- name: installing dotnet7 on ubuntu and centos
  become: yes
  hosts: all
  tasks:
    - name: installing dotnet7 on ubuntu
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/config/ubuntu/22.10/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: installing packages-microsoft-prod.deb package
      ansible.builtin.apt:
        name: deb=/tmp/packages-microsoft-prod.deb
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: setiing https
      ansible.builtin.apt:
        name: apt-transport-https
        update_cache: yes
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: installing dotnet
      ansible.builtin.apt:
        name: dotnet-sdk-7.0
        update_cache: yes
        state: present
      when: ansible_facts['distribution'] == "Ubuntu" 