---
- name: install java 11 on centos and ubuntu
  become: yes
  hosts: all
  tasks: 
    - name: installing java on ubuntu
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: installing java on centos
      ansible.builtin.yum:
        name: java-11-openjdk-devel
        state: present
        update_cache: yes
      when: ansible_facts['distribution'] == "CentOS"