---
- name: installing nodejs on ubuntu and centos
  become: yes
  hosts: all
  tasks:
    - name: installing  nodejs on ubuntu
      ansible.builtin.apt:
        name: nodejs
        state: present
    - name: installing nodejs on centos
      ansible.builtin.get_url:
        url: https://rpm.nodesource.com/setup_10.x
        dest: /opt/nodesetup
        mode: "777"
      when: ansible_facts['distribution'] == "CentOS"
    - name: giving shell permissions
      shell: /opt/nodesetup

    
